server:
  port: 8081

  management:
    endpoints:
      web:
        exposure:
          include: "*"

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: google
          uri: https://google.com
          predicates:
            - Path=/search**